import { PrismaClient } from '@prisma/client';
import { hashPassword } from '../lib/auth';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed...');

  // Create demo users
  const hashedPassword = await hashPassword('password123');
  
  const user1 = await prisma.user.upsert({
    where: { email: 'john@example.com' },
    update: {},
    create: {
      name: 'John Doe',
      email: 'john@example.com',
      password: hashedPassword,
    },
  });

  const user2 = await prisma.user.upsert({
    where: { email: 'sarah@techstartup.com' },
    update: {},
    create: {
      name: 'Sarah Chen',
      email: 'sarah@techstartup.com',
      password: hashedPassword,
    },
  });

  console.log('✅ Created demo users');

  // Create demo startups
  const startup1 = await prisma.startup.create({
    data: {
      name: 'TechFlow',
      domain: 'techflow.com',
      stage: 'GROWTH',
      description: 'AI-powered workflow automation for modern teams',
      logo: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop',
      founded: '2022',
      location: 'San Francisco, CA',
      employees: '25-50',
      funding: 'Series A',
      website: 'https://techflow.com',
      industry: 'SaaS',
      upvotes: 15,
      downvotes: 2,
      userId: user2.id,
    },
  });

  const startup2 = await prisma.startup.create({
    data: {
      name: 'DataViz Pro',
      domain: 'datavizpro.com',
      stage: 'MVP',
      description: 'Beautiful data visualization tools for businesses',
      logo: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop',
      founded: '2023',
      location: 'New York, NY',
      employees: '5-10',
      funding: 'Seed',
      website: 'https://datavizpro.com',
      industry: 'Analytics',
      upvotes: 8,
      downvotes: 1,
      userId: user1.id,
    },
  });

  console.log('✅ Created demo startups');

  // Create demo jobs
  await prisma.job.createMany({
    skipDuplicates: true,
    data: [
      {
        title: 'Senior Frontend Developer',
        location: 'San Francisco, CA',
        type: 'FULL_TIME',
        description: 'Join our growing team to build the future of workflow automation...',
        requirements: ['React', 'TypeScript', 'Next.js', '5+ years experience'],
        experienceLevel: 'SENIOR',
        salaryMin: 120000,
        salaryMax: 160000,
        remote: true,
        startupId: startup1.id,
      },
      {
        title: 'Product Designer',
        location: 'San Francisco, CA',
        type: 'FULL_TIME',
        description: 'Design beautiful and intuitive user experiences...',
        requirements: ['Figma', 'User Research', 'Prototyping', '3+ years experience'],
        experienceLevel: 'MID',
        salaryMin: 90000,
        salaryMax: 130000,
        remote: true,
        startupId: startup1.id,
      },
    ],
  });

  console.log('✅ Created demo jobs');

  // Create demo investors
  await prisma.investor.createMany({
    skipDuplicates: true,
    data: [
      {
    name: 'Anupam Mittal',
    firm: 'Shaadi.com / Angel',
    preferredStage: ['Seed', 'Series A'],
    sectors: ['Consumer', 'Mobility', 'Fintech'],
    geography: ['India'],
    description: 'Founder‑CEO of Shaadi.com and Shark Tank India judge; invested in 250+ startups.',
    portfolio: ['Ola', 'BigBasket', 'WhatFix'],
    email: '',
    linkedin: 'https://linkedin.com/in/anupammittal',
    imageUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
  },
  {
    name: 'Kunal Shah',
    firm: 'CRED / Angel',
    preferredStage: ['Pre-seed', 'Seed'],
    sectors: ['Fintech', 'Consumer', 'SaaS'],
    geography: ['India'],
    description: 'Founder of CRED; backed 200+ startups including Razorpay, Unacademy.',
    portfolio: ['Razorpay', 'Unacademy', 'BharatPe'],
    email: '',
    linkedin: 'https://linkedin.com/in/kunal-shah-cred',
    imageUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
  },
  {
    name: 'Rajan Anandan',
    firm: 'Peak XV Partners',
    preferredStage: ['Seed', 'Series A'],
    sectors: ['AI', 'SaaS', 'Marketplace'],
    geography: ['India', 'SEA'],
    description: 'Ex‑Google India MD and Surge head; early backer of WebEngage, Dunzo.',
    portfolio: ['WebEngage', 'Dunzo', 'Instamojo'],
    email: '',
    linkedin: 'https://linkedin.com/in/rajananandan',
    imageUrl: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
  },
  {
    name: 'Sanjay Mehta',
    firm: '100X.VC / Mumbai Angels',
    preferredStage: ['Pre-seed', 'Seed'],
    sectors: ['Fintech', 'DeepTech', 'SaaS'],
    geography: ['India'],
    description: 'Pioneer of iSAFE in India; backed Oyo, CoinDCX, AXIOM Space.',
    portfolio: ['Oyo', 'CoinDCX', 'AXIOM Space'],
    email: '',
    linkedin: 'https://linkedin.com/in/sanjaymehta',
    imageUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
  },
  {
    name: 'Kunal Bahl',
    firm: 'Titan Capital',
    preferredStage: ['Seed', 'Series A'],
    sectors: ['Consumer', 'D2C', 'SaaS'],
    geography: ['India'],
    description: 'Snapdeal cofounder; invests in consumer & SaaS startups.',
    portfolio: ['Mamaearth', 'UrbanClap', 'Razorpay'],
    email: '',
    linkedin: 'https://linkedin.com/in/kunalbahl',
    imageUrl: 'https://images.pexels.com/photos/331240/pexels-photo-331240.jpeg',
  },
  {
    name: 'Ashneer Grover',
    firm: 'Angel / BharatPe',
    preferredStage: ['Seed'],
    sectors: ['Fintech', 'FoodTech', 'HealthTech'],
    geography: ['India'],
    description: 'BharatPe cofounder turned active angel investor in fintech.',
    portfolio: ['YAP', 'Fello', 'India Gold'],
    email: '',
    linkedin: '',
    imageUrl: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
  },
  {
    name: 'MS Dhoni',
    firm: 'Celebrity / Angel',
    preferredStage: ['Seed'],
    sectors: ['EV', 'DroneTech', 'HealthTech'],
    geography: ['India'],
    description: 'Legendary cricketer who invests in EVs, drones, wellness startups.',
    portfolio: ['Garuda Aerospace', 'BluSmart Mobility'],
    email: '',
    linkedin: '',
    imageUrl: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
  },
  {
    name: 'Ritesh Agarwal',
    firm: 'OYO / Angel',
    preferredStage: ['Pre-seed', 'Seed'],
    sectors: ['PropTech', 'TravelTech', 'Hospitality'],
    geography: ['India'],
    description: 'OYO founder and Shark Tank India judge backing early‑stage startups.',
    portfolio: ['LimeChat', 'GrowthSchool'],
    email: '',
    linkedin: 'https://linkedin.com/in/riteshagar',
    imageUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
  },
  {
    name: 'Vijay Shekhar Sharma',
    firm: 'Paytm / Angel',
    preferredStage: ['Seed', 'Series A'],
    sectors: ['Fintech', 'EdTech', 'Mobility'],
    geography: ['India'],
    description: 'Paytm founder; invests in mobility, edtech & fintech startups.',
    portfolio: ['Ola Electric', 'Karkinos'],
    email: '',
    linkedin: 'https://linkedin.com/in/vijayshekhar',
    imageUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
  },
  {
    name: 'Sachin Bansal',
    firm: 'Flipkart / Angel',
    preferredStage: ['Seed', 'Series A'],
    sectors: ['Fintech', 'Mobility', 'AI'],
    geography: ['India'],
    description: 'Flipkart cofounder; invests via Navi in SaaS, mobility & AI.',
    portfolio: ['Inshorts', 'Ola Electric'],
    email: '',
    linkedin: 'https://linkedin.com/in/sachinbansal',
    imageUrl: 'https://images.pexels.com/photos/331240/pexels-photo-331240.jpeg',
  },
  {
    name: 'Anjali Bansal',
    firm: 'Avaana Capital',
    preferredStage: ['Seed', 'Series A'],
    sectors: ['CleanTech', 'Climate', 'Sustainability'],
    geography: ['India'],
    description: 'Founder of Avaana Capital; focuses on cleantech & climate tech.',
    portfolio: [],
    email: '',
    linkedin: 'https://linkedin.com/in/anjalibansal',
    imageUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
  },
  {
    name: 'Sashi Reddi',
    firm: 'SRI Capital / Angel',
    preferredStage: ['Seed', 'Series A'],
    sectors: ['Enterprise Software', 'DeepTech', 'SaaS'],
    geography: ['India', 'US'],
    description: 'Founder of AppLabs & SRI Capital; invests in enterprise and deeptech.',
    portfolio: [],
    email: '',
    linkedin: '',
    imageUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
  },
  {
    name: 'Naveen Tewari',
    firm: 'InMobi / Angel',
    preferredStage: ['Pre-seed', 'Seed'],
    sectors: ['AdTech', 'Mobile', 'AI'],
    geography: ['India', 'US'],
    description: 'Founder of InMobi; invested in 30+ startups across mobile and AI.',
    portfolio: [],
    email: '',
    linkedin: '',
    imageUrl: 'https://images.pexels.com/photos/331240/pexels-photo-331240.jpeg',
  },
  {
    name: 'Rehan Yar Khan',
    firm: 'Angel Investor',
    preferredStage: ['Seed'],
    sectors: ['Consumer', 'Tech', 'Marketplace'],
    geography: ['India'],
    description: 'Investor featured in YourStory profile; backs marketplace startups.',
    portfolio: [],
    email: '',
    linkedin: '',
    imageUrl: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
  },
  {
    name: 'Akshay Singhal',
    firm: 'Angel / Energy',
    preferredStage: ['Seed'],
    sectors: ['Energy', 'CleanTech'],
    geography: ['India'],
    description: 'Top energy angel investor in India with multiple energy startup deals.',
    portfolio: [],
    email: '',
    linkedin: '',
    imageUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
  },
  {
    name: 'Kris Gopalakrishnan',
    firm: 'Angel / Infosys Cofounder',
    preferredStage: ['Seed', 'Series A'],
    sectors: ['AI', 'DeepTech', 'HealthTech'],
    geography: ['India'],
    description: 'Infosys cofounder; invests in AI, deeptech, healthtech startups.',
    portfolio: [],
    email: '',
    linkedin: '',
    imageUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
  },
  {
    name: 'Gaurav Juneja',
    firm: 'Angel / Energy',
    preferredStage: ['Seed'],
    sectors: ['Energy', 'ClimateTech'],
    geography: ['India'],
    description: 'Active investor in clean energy startups in India.',
    portfolio: [],
    email: '',
    linkedin: '',
    imageUrl: 'https://images.pexels.com/photos/331240/pexels-photo-331240.jpeg',
  },
  {
    name: 'Sagar Ratilal Bavarva',
    firm: 'Angel / Energy',
    preferredStage: ['Seed'],
    sectors: ['Energy', 'CleanTech'],
    geography: ['India'],
    description: 'Energy-focused angel with multiple investments in climate tech.',
    portfolio: [],
    email: '',
    linkedin: '',
    imageUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
  },
  {
    name: 'Naham Kshatriya',
    firm: 'Angel / Energy',
    preferredStage: ['Seed'],
    sectors: ['Energy', 'CleanTech'],
    geography: ['India'],
    description: 'Clean energy angel investor featured in top50 list.',
    portfolio: [],
    email: '',
    linkedin: '',
    imageUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
  },
  {
    name: 'Shashank Randev',
    firm: 'Angel / Energy',
    preferredStage: ['Seed'],
    sectors: ['Energy', 'ClimateTech'],
    geography: ['India'],
    description: 'Angel investor in energy startups, part of top‑50 energy angels.',
    portfolio: [],
    email: '',
    linkedin: '',
    imageUrl: 'https://images.pexels.com/photos/331240/pexels-photo-331240.jpeg',
  },
    ],
  });

  console.log('✅ Created demo investors');

  // Create demo incubators
  await prisma.incubator.createMany({
    skipDuplicates: true,
    data: [
      {
        name: "CIIE.CO - IIM Ahmedabad",
        logo: null,
        description: "One of India's leading startup incubators supporting early-stage innovation across sectors.",
        location: "Ahmedabad, Gujarat",
        focusAreas: ["Fintech", "Agritech", "Healthcare", "Social Impact"],
        website: "https://ciie.co/",
        applyLink: "https://ciie.co/entrepreneurs/",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "NSRCEL - IIM Bangalore",
        logo: null,
        description: "NSRCEL at IIMB supports startups from ideation to scale with dedicated sectoral programs.",
        location: "Bangalore, Karnataka",
        focusAreas: ["Women-led Startups", "Mobility", "Fintech", "Healthtech"],
        website: "https://nsrcel.org/",
        applyLink: "https://nsrcel.org/apply-now/",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "T-Hub",
        logo: null,
        description: "India’s largest innovation hub, supporting tech-based startups through mentorship and funding.",
        location: "Hyderabad, Telangana",
        focusAreas: ["DeepTech", "AI/ML", "IoT", "HealthTech"],
        website: "https://t-hub.co/",
        applyLink: "https://t-hub.co/startups/",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "SINE - IIT Bombay",
        logo: null,
        description: "Society for Innovation and Entrepreneurship at IIT Bombay supporting deep tech ventures.",
        location: "Mumbai, Maharashtra",
        focusAreas: ["Robotics", "CleanTech", "AI/ML", "Engineering"],
        website: "https://www.sineiitb.org/",
        applyLink: "https://www.sineiitb.org/incubation-apply",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Forge Accelerator",
        logo: null,
        description: "Innovation accelerator from Coimbatore that works with industry-driven tech solutions.",
        location: "Coimbatore, Tamil Nadu",
        focusAreas: ["Industry 4.0", "Manufacturing", "IoT"],
        website: "https://forgeforward.in/",
        applyLink: "https://forgeforward.in/apply/",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Startup Oasis",
        logo: null,
        description: "Startup incubator in Jaipur promoting entrepreneurship in tier-2 cities.",
        location: "Jaipur, Rajasthan",
        focusAreas: ["Social Enterprises", "Tech for Good", "EdTech"],
        website: "https://startupoasis.in/",
        applyLink: "https://startupoasis.in/#contact",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "DERBI Foundation",
        logo: null,
        description: "Tech startup incubator supported by DST, focusing on early-stage deep-tech startups.",
        location: "Bangalore, Karnataka",
        focusAreas: ["DeepTech", "IoT", "MedTech"],
        website: "https://derbifoundation.com/",
        applyLink: "https://derbifoundation.com/contact-us/",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "AIC - Banasthali Vidyapith",
        logo: null,
        description: "Women-centric startup incubator supporting ventures from across India.",
        location: "Banasthali, Rajasthan",
        focusAreas: ["Women-led Startups", "Social Impact", "Sustainability"],
        website: "https://aicbanasthali.org/",
        applyLink: "https://aicbanasthali.org/#contact",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "AIC - Manipal University Jaipur (AIC-MUJ)",
        logo: null,
        description: "AIC–MUJ is an Atal Innovation Mission-backed incubator by Manipal University Jaipur. It supports early-stage startups with mentorship, co-working space, and access to labs in AR/VR, DeepTech, and healthcare.",
        location: "Jaipur, Rajasthan",
        focusAreas: ["AR/VR", "DeepTech", "Healthcare", "Sustainability", "Environmental Health"],
        website: "https://www.aicmuj.com/",
        applyLink: "https://connect.aicmuj.com/",
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ]
  });

  console.log('✅ Created demo incubators');

  // ✅ Create merged resources (from your original resource list)
  await prisma.resource.createMany({
    skipDuplicates: true,
    data: [
      {
        title: `Y Combinator Startup Library`,
        description: `Comprehensive resources from YC for startups at every stage.`,
        category: "STARTUP_GUIDES",
        type: "LINK",
        url: "https://www.ycombinator.com/library",
        imageUrl: "https://img.startupconnect.in/resources/y.jpg",
        featured: true,
        createdAt: new Date('2025-07-15T13:22:51.184570'),
        updatedAt: new Date('2025-07-15T13:22:51.184582'),
      },
      {
        title: `Startup School by YC`,
        description: `Free online course and community for startup founders.`,
        category: "STARTUP_GUIDES",
        type: "COURSE",
        url: "https://www.startupschool.org/",
        imageUrl: "https://img.startupconnect.in/resources/startup.jpg",
        featured: true,
        createdAt: new Date('2025-07-15T13:22:51.185030'),
        updatedAt: new Date('2025-07-15T13:22:51.185040'),
      },
      {
        title: `Founder's Handbook (Notion)`,
        description: `A public Notion handbook covering early founder decisions, tools, and tips.`,
        category: "STARTUP_GUIDES",
        type: "TEMPLATE",
        url: "https://www.notion.so/Founder-s-Startup-Handbook-020b7107c760456da1db872fba5b1bba",
        imageUrl: "https://img.startupconnect.in/resources/founder's.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.185336'),
        updatedAt: new Date('2025-07-15T13:22:51.185343'),
      },
      {
        title: `100X.VC Resource Hub`,
        description: `VC firm offering guides and pitch formats for Indian startups.`,
        category: "FUNDING_RESOURCES",
        type: "LINK",
        url: "https://www.100x.vc/resource-hub",
        imageUrl: "https://img.startupconnect.in/resources/100x.vc.jpg",
        featured: true,
        createdAt: new Date('2025-07-15T13:22:51.185570'),
        updatedAt: new Date('2025-07-15T13:22:51.185573'),
      },
      {
        title: `Startup India Seed Fund Scheme`,
        description: `Govt. scheme to support early-stage startups with seed funding.`,
        category: "FUNDING_RESOURCES",
        type: "LINK",
        url: "https://seedfund.startupindia.gov.in/",
        imageUrl: "https://img.startupconnect.in/resources/startup.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.185633'),
        updatedAt: new Date('2025-07-15T13:22:51.185635'),
      },
      {
        title: `AngelList India`,
        description: `Platform to discover Indian angel investors and syndicates.`,
        category: "FUNDING_RESOURCES",
        type: "PLATFORM",
        url: "https://angel.co/india",
        imageUrl: "https://img.startupconnect.in/resources/angellist.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.185780'),
        updatedAt: new Date('2025-07-15T13:22:51.185786'),
      },
      {
        title: `JD Templates for Startups`,
        description: `Pre-built job description templates for tech and non-tech roles.`,
        category: "HIRING_TEAM",
        type: "TEMPLATE",
        url: "https://resources.workable.com/job-description-templates",
        imageUrl: "https://img.startupconnect.in/resources/jd.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186079'),
        updatedAt: new Date('2025-07-15T13:22:51.186087'),
      },
      {
        title: `AngelList Talent`,
        description: `Hire startup-ready talent from a global pool.`,
        category: "HIRING_TEAM",
        type: "PLATFORM",
        url: "https://angel.co/talent",
        imageUrl: "https://img.startupconnect.in/resources/angellist.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186139'),
        updatedAt: new Date('2025-07-15T13:22:51.186141'),
      },
      {
        title: `ESOP Toolkit by Razorpay`,
        description: `Understand, manage, and distribute ESOPs effectively.`,
        category: "HIRING_TEAM",
        type: "TOOLKIT",
        url: "https://razorpay.com/learn/esop-toolkit-startups/",
        imageUrl: "https://img.startupconnect.in/resources/esop.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186164'),
        updatedAt: new Date('2025-07-15T13:22:51.186165'),
      },
      {
        title: `Growth Hacking Guide for Startups`,
        description: `Learn scrappy marketing strategies to grow fast.`,
        category: "MARKETING_BRANDING",
        type: "ARTICLE",
        url: "https://neilpatel.com/blog/startup-marketing/",
        imageUrl: "https://img.startupconnect.in/resources/growth.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186183'),
        updatedAt: new Date('2025-07-15T13:22:51.186185'),
      },
      {
        title: `Landing Page Teardowns`,
        description: `Understand what makes great startup landing pages work.`,
        category: "MARKETING_BRANDING",
        type: "VIDEO",
        url: "https://www.youtube.com/playlist?list=PLn2e1F9Rfr6lpVddr04mI-vNjTjD9E8bZ",
        imageUrl: "https://img.startupconnect.in/resources/landing.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186205'),
        updatedAt: new Date('2025-07-15T13:22:51.186208'),
      },
      {
        title: `GitHub for Startups`,
        description: `Free GitHub enterprise tools for qualifying startups.`,
        category: "TECH_TOOLS",
        type: "PROGRAM",
        url: "https://github.com/organizations/startups",
        imageUrl: "https://img.startupconnect.in/resources/github.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186220'),
        updatedAt: new Date('2025-07-15T13:22:51.186222'),
      },
      {
        title: `Notion for Startups Program`,
        description: `Up to $1,000 in credits for early-stage startups.`,
        category: "TECH_TOOLS",
        type: "PROGRAM",
        url: "https://www.notion.so/startups",
        imageUrl: "https://img.startupconnect.in/resources/notion.jpg",
        featured: true,
        createdAt: new Date('2025-07-15T13:22:51.186233'),
        updatedAt: new Date('2025-07-15T13:22:51.186234'),
      },
      {
        title: `Stripe Atlas`,
        description: `Incorporate your startup in the US with ease.`,
        category: "TECH_TOOLS",
        type: "SERVICE",
        url: "https://stripe.com/atlas",
        imageUrl: "https://img.startupconnect.in/resources/stripe.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186404'),
        updatedAt: new Date('2025-07-15T13:22:51.186411'),
      },
      {
        title: `Product Management for Startups`,
        description: `Free course by Reforge and First Round Capital.`,
        category: "LEARNING",
        type: "COURSE",
        url: "https://www.reforge.com",
        imageUrl: "https://img.startupconnect.in/resources/product.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186620'),
        updatedAt: new Date('2025-07-15T13:22:51.186626'),
      },
      {
        title: `Indie Hackers Podcast`,
        description: `Stories and lessons from solo and startup founders.`,
        category: "LEARNING",
        type: "PODCAST",
        url: "https://www.indiehackers.com/podcast",
        imageUrl: "https://img.startupconnect.in/resources/indie.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186703'),
        updatedAt: new Date('2025-07-15T13:22:51.186708'),
      },
      {
        title: `Founders' Network India`,
        description: `WhatsApp and Slack groups for Indian founders.`,
        category: "COMMUNITY",
        type: "COMMUNITY",
        url: "https://www.founders-network.com/",
        imageUrl: "https://img.startupconnect.in/resources/founders'.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186736'),
        updatedAt: new Date('2025-07-15T13:22:51.186738'),
      },
      {
        title: `TiE Chapters in India`,
        description: `TiE's chapters connecting startups with mentors.`,
        category: "COMMUNITY",
        type: "DIRECTORY",
        url: "https://tie.org/chapters/",
        imageUrl: "https://img.startupconnect.in/resources/tie.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186748'),
        updatedAt: new Date('2025-07-15T13:22:51.186749'),
      },
      {
        title: `Startup India Portal`,
        description: `Central portal for Indian startup registration, schemes, benefits.`,
        category: "GOVERNMENT",
        type: "PORTAL",
        url: "https://www.startupindia.gov.in/",
        imageUrl: "https://img.startupconnect.in/resources/startup.jpg",
        featured: true,
        createdAt: new Date('2025-07-15T13:22:51.186758'),
        updatedAt: new Date('2025-07-15T13:22:51.186760'),
      },
      {
        title: `Register a Private Limited Company in India`,
        description: `Step-by-step guide to registering your startup.`,
        category: "GOVERNMENT",
        type: "ARTICLE",
        url: "https://www.indiafilings.com/learn/private-limited-company-registration/",
        imageUrl: "https://img.startupconnect.in/resources/register.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186769'),
        updatedAt: new Date('2025-07-15T13:22:51.186771'),
      },
      {
        title: `Case Studies on Indian Unicorns`,
        description: `In-depth analysis of companies like Zerodha, Zomato, Paytm.`,
        category: "CASE_STUDIES",
        type: "BLOG",
        url: "https://ajuniorvc.com/",
        imageUrl: "https://img.startupconnect.in/resources/case.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186780'),
        updatedAt: new Date('2025-07-15T13:22:51.186782'),
      },
      {
        title: `Startup Post-Mortems`,
        description: `Why 100+ startups failed – and what we can learn.`,
        category: "CASE_STUDIES",
        type: "COLLECTION",
        url: "https://www.failory.com/cause-of-failure",
        imageUrl: "https://img.startupconnect.in/resources/startup.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:22:51.186806'),
        updatedAt: new Date('2025-07-15T13:22:51.186808'),
      },
      {
        title: `How to Build an MVP`,
        description: `A practical guide to building and launching your MVP quickly.`,
        category: "STARTUP_GUIDES",
        type: "ARTICLE",
        url: "https://mvp.dev/guide",
        imageUrl: "https://img.startupconnect.in/resources/how.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.486526'),
        updatedAt: new Date('2025-07-15T13:18:57.486536'),
      },
      {
        title: `Pitch Deck Template`,
        description: `Use this clean deck template to pitch your startup idea.`,
        category: "FUNDING_RESOURCES",
        type: "TEMPLATE",
        url: "https://slidesgo.com/startup-pitch-deck",
        imageUrl: "https://img.startupconnect.in/resources/pitch.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.486632'),
        updatedAt: new Date('2025-07-15T13:18:57.486644'),
      },
      {
        title: `Hiring First 10 Employees`,
        description: `What to look for when building your early team.`,
        category: "HIRING_TEAM",
        type: "ARTICLE",
        url: "https://firstround.com/articles/hiring-your-first-employees",
        imageUrl: "https://img.startupconnect.in/resources/hiring.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.486714'),
        updatedAt: new Date('2025-07-15T13:18:57.486724'),
      },
      {
        title: `Startup Marketing 101`,
        description: `Learn the basics of early-stage marketing for founders.`,
        category: "MARKETING_BRANDING",
        type: "COURSE",
        url: "https://coursera.org/learn/startup-marketing",
        imageUrl: "https://img.startupconnect.in/resources/startup.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.486757'),
        updatedAt: new Date('2025-07-15T13:18:57.486759'),
      },
      {
        title: `Free Tools for Startups`,
        description: `A curated list of free tools useful for early-stage startups.`,
        category: "TECH_TOOLS",
        type: "COLLECTION",
        url: "https://free-for.dev/",
        imageUrl: "https://img.startupconnect.in/resources/free.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.486773'),
        updatedAt: new Date('2025-07-15T13:18:57.486775'),
      },
      {
        title: `Startup Legal Checklist`,
        description: `Everything a startup should prepare legally from Day 1.`,
        category: "GOVERNMENT",
        type: "ARTICLE",
        url: "https://startupindia.gov.in/legal-checklist",
        imageUrl: "https://img.startupconnect.in/resources/startup.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.486807'),
        updatedAt: new Date('2025-07-15T13:18:57.486809'),
      },
      {
        title: `India’s Top Incubators`,
        description: `List of top startup incubators across India.`,
        category: "COMMUNITY",
        type: "DIRECTORY",
        url: "https://yourstory.com/2022/04/incubators-india",
        imageUrl: "https://img.startupconnect.in/resources/india’s.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.486834'),
        updatedAt: new Date('2025-07-15T13:18:57.486837'),
      },
      {
        title: `Startup Case Studies PDF`,
        description: `PDF collection of startup case studies from India.`,
        category: "CASE_STUDIES",
        type: "BLOG",
        url: "https://startupindia.gov.in/case-studies",
        imageUrl: "https://img.startupconnect.in/resources/startup.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.486868'),
        updatedAt: new Date('2025-07-15T13:18:57.486874'),
      },
      {
        title: `Top Startup Podcasts`,
        description: `Listen to startup journeys, failures, and insights.`,
        category: "LEARNING",
        type: "PODCAST",
        url: "https://open.spotify.com/show/startup-podcast",
        imageUrl: "https://img.startupconnect.in/resources/top.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.486906'),
        updatedAt: new Date('2025-07-15T13:18:57.486908'),
      },
      {
        title: `Startup Grants in India`,
        description: `Government and private grants available for Indian startups.`,
        category: "FUNDING_RESOURCES",
        type: "PORTAL",
        url: "https://startupindia.gov.in/grants",
        imageUrl: "https://img.startupconnect.in/resources/startup.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.486924'),
        updatedAt: new Date('2025-07-15T13:18:57.486929'),
      },
      {
        title: `Startup Competition List`,
        description: `Annual competitions where startups can pitch and win.`,
        category: "COMMUNITY",
        type: "COLLECTION",
        url: "https://f6s.com/programs",
        imageUrl: "https://img.startupconnect.in/resources/startup.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.487125'),
        updatedAt: new Date('2025-07-15T13:18:57.487128'),
      },
      {
        title: `Remote Team Tools`,
        description: `Best tools to manage your remote team.`,
        category: "TECH_TOOLS",
        type: "ARTICLE",
        url: "https://zapier.com/blog/tools-remote-teams",
        imageUrl: "https://img.startupconnect.in/resources/remote.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.487158'),
        updatedAt: new Date('2025-07-15T13:18:57.487160'),
      },
      {
        title: `UX Design Tips for Startups`,
        description: `How to build simple, lovable, complete products.`,
        category: "MARKETING_BRANDING",
        type: "ARTICLE",
        url: "https://nngroup.com/articles/startup-ux",
        imageUrl: "https://img.startupconnect.in/resources/ux.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.487169'),
        updatedAt: new Date('2025-07-15T13:18:57.487170'),
      },
      {
        title: `Early Employee Equity`,
        description: `How much equity should you give to early hires?`,
        category: "HIRING_TEAM",
        type: "ARTICLE",
        url: "https://avc.com/2020/10/the-employee-equity-equation",
        imageUrl: "https://img.startupconnect.in/resources/early.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.487179'),
        updatedAt: new Date('2025-07-15T13:18:57.487180'),
      },
      {
        title: `Startup Compliance 2025`,
        description: `Ensure you meet updated legal regulations in India.`,
        category: "GOVERNMENT",
        type: "ARTICLE",
        url: "https://vakilsearch.com/startup-compliance",
        imageUrl: "https://img.startupconnect.in/resources/startup.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.487188'),
        updatedAt: new Date('2025-07-15T13:18:57.487190'),
      },
      {
        title: `AI Tools for Founders`,
        description: `List of AI tools that help founders build faster.`,
        category: "TECH_TOOLS",
        type: "COLLECTION",
        url: "https://theresanaiforthat.com/startups",
        imageUrl: "https://img.startupconnect.in/resources/ai.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.487198'),
        updatedAt: new Date('2025-07-15T13:18:57.487199'),
      },
      {
        title: `India's Unicorn Tracker`,
        description: `Track unicorns and high-growth startups.`,
        category: "CASE_STUDIES",
        type: "PORTAL",
        url: "https://tracxn.com/explore/Unicorns",
        imageUrl: "https://img.startupconnect.in/resources/india's.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.487207'),
        updatedAt: new Date('2025-07-15T13:18:57.487209'),
      },
      {
        title: `How Startups Fail`,
        description: `Breakdown of top reasons why startups fail.`,
        category: "CASE_STUDIES",
        type: "ARTICLE",
        url: "https://failory.com/blog/startup-failure-reasons",
        imageUrl: "https://img.startupconnect.in/resources/how.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.487217'),
        updatedAt: new Date('2025-07-15T13:18:57.487219'),
      },
      {
        title: `Register LLP in India`,
        description: `Step-by-step to register an LLP startup in India.`,
        category: "GOVERNMENT",
        type: "ARTICLE",
        url: "https://vakilsearch.com/llp-registration",
        imageUrl: "https://img.startupconnect.in/resources/register.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.487228'),
        updatedAt: new Date('2025-07-15T13:18:57.487229'),
      },
      {
        title: `Women in Startups`,
        description: `Resources and communities for women-led startups.`,
        category: "COMMUNITY",
        type: "DIRECTORY",
        url: "https://weconnectinternational.org",
        imageUrl: "https://img.startupconnect.in/resources/women.jpg",
        featured: false,
        createdAt: new Date('2025-07-15T13:18:57.487237'),
        updatedAt: new Date('2025-07-15T13:18:57.487238'),
      },
    ]
  });

  console.log('✅ Created merged resources');

  // Create demo feedback
  await prisma.startupFeedback.create({
    data: {
      comment: 'Great product! Really helps with our team workflow.',
      userId: user1.id,
      startupId: startup1.id,
    },
  });

  console.log('✅ Created demo feedback');

  console.log('🎉 Database seeded successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
